### ISSUE TITLE
Allow adding arbitrary attributes

### ISSUE THREAD

**Issue by AngellusMortis** [newrelic/junit-reporter-action#7]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

It would be nice if we can provide arbitrary attributes to the `TestRun` objects to help with filtering and dashboarding. 

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

```yml
      - name: Post JUnit test results to New Relic
        uses: newrelic/junit-reporter-action@v0.2
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          ingestLicenseKey: ${{ secrets.NEW_RELIC_INGEST_LICENSE_KEY }}
          testOutputPath: test-output/integration.xml
          attributes: |-
               ref=${{ github.ref }}
               sha=${{ github.sha }}
```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

If you have a mono repo and multiple test runners inside of a single repo, or multiple repos going into a single New Relic app, it is not really possible to tell which `TestRun` objects are for which runner.
